project:
  type: website

website:
  title: "Math 401"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: docked
    search: true
    contents:
      - section: "Gaussian Processes"
        href: "./gaussian_processes/index.qmd"
        contents:
          - "./gaussian_processes/mvnorm/index.qmd"
          - "./gaussian_processes/gaussian_process_regression/index.qmd"
      - text: "Kernel Ridge Regression"
        href: "./krr/index.qmd"
      - section: "Reflections"
        href: "./reflections/index.qmd"
        contents:
          - "./reflections/reflection_1.qmd"


execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
