project:
  type: website

website:
  title: "Math 401"
  navbar:
    left:
      - href: index.qmd
        text: Home

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
