---
title: Gaussian Processes and Gaussian Process Regression
---

## Gaussian Processes

Elsewhere, I described [the multivariate Gaussian distribution](../mvnorm/index.qmd), which can be used to model random vectors of jointly distributed Gaussian random variables. A *Gaussian Process* (GP) can be used to model functions over arbitrarily sized sets. They're an extension of the multivariate Gaussian, in which we move from thinking about vectors of a fixed dimension to functions that describe random vectors of any (potentially infinite) size. GPs are parameterized with a *mean function* and *covariance kernel*, rather than a fixed mean vector $\mu$ and covariance matrix $\mathbf{\Sigma}$.

### Definition: Stochastic Process (or, random function)



### Definition: Gaussian Process

Let $\chi$ be a nonempty set, $k: \chi \times \chi \to \mathbb{R}$ a positive definite kernel and $m: \chi \to \mathbb{R}$ be any real-valued function. Then, a random function $f: \chi \to \mathbb{R}$ is said to be a Gaussian process (GP) with *mean function* $m$ and *covariance kernel* $k$, denoted by $\mathcal{GP}(m, k)$, if the following holds: For any finite set $X = (x_1, \dots, x_n) \subset \chi$ of any size $n \in \mathbb{N}$, the random vector

$$
f_X = (f(x_1), \dots, f(x_n))^\top \in \mathbb{R}^n
$$

follows the multivariate normal distribution $\mathcal{N}(m_X, k_{XX})$ with covariance matrix $k_{XX} = [k(x_i, x_j)]_{i, j = 1}^{n} \in \mathbb{R}^{n \times n}$ and mean vector $m_X = (m(x_1), \dots, m(x_n))^\top$.

### Remarks

By convention, the zero function is used for $m(x)$, allowing the GP to be fully described by the choice of kernel (and any associated hyperparameters).

## Gaussian Process Regression

