---
title: Reflection 1
author: Andrew Moore
date: "1/31/2025"
format:
  pdf:
    margin-top: 30mm
    margin-bottom: 30mm
    margin-left: 30mm
    margin-right: 30mm
  html: default
bibliography: reflection_1.bib
description: |
  This reflection asks the student to analyze their undergraduate transcript in order to develop a
  "big picture" view of their coursework completed during their program.
---

A key aspect of my experience at Boise state is that I am a second-degree student. My first B.A. degree was in the field of psychology. After graduating in 2013, I worked as a research technician in various settings and as a data analyst. Coursework and independent research experience from my first degree prepared me for the work I would perform, but I was constantly drawn to the study of mathematics and statistical science. Modern software makes computing and visualizing statistical data quick and often easy to perform. To me, this convenience highlights the importance of understanding the fundamentals beneath a software implementation. I was computing summaries and building/visualizing small statistical models. I wanted to make sure that I wasn't mishandling these "golems", as Richard McElreath [@mcelreath2018statistical chapter 1] describes them.

When I began my program at Boise State, I had already completed Calculus I, Calculus II, Calculus III, and an introduction to Linear Algebra. I believe there are two themes visible in my coursework, and will elaborate on them in the following paragraphs. Below is a list of courses I completed during my second degree, with courses as part of the statistics emphasis in *italics* and courses I want to highlight in **bold**.

| Term        | Course   | Title                                     |
| :---------- | :------- | :---------------------------------------- |
| 2021 Spring | MATH 361 | Probability & Statistics I                |
| 2021 Summer | MATH 189 | Discrete Mathematics                      |
| 2021 Fall   | MATH 287 | **Mathematical Proofs & Methods**         |
|             | MATH 471 | *Data Analysis*                           |
| 2022 Spring | MATH 305 | Abstract Algebra/Number Theory            |
|             | MATH 314 | **Foundations of Analysis**               |
| 2022 Fall   | MATH 333 | Differential Equations w/ Matrix Theory   |
|             | MATH 462 | ***Probability & Statistics II***         |
| 2023 Spring | MATH 472 | ***Computational Statistics***            |
| 2023 Fall   | MATH 365 | Introduction to Computational Mathematics |
| 2024 Spring | MATH 308 | Introduction to Algebraic Cryptology      |
| 2024 Fall   | MATH 403 | Linear Algebra                            |
|             | MATH 465 | **Introduction to Numerical Methods**     |

The first theme is the development of literacy for mathematical writing. I greatly appreciated the first few classes I took that emphasized the examination and writing of mathematical proofs. I remember MATH 287, MATH 305, and MATH 314 being very challenging, but deeply rewarding in terms of strengthening my ability to read and decompose theorems that I'd encounter in other classes. I credit MATH 287 in particular for helping me learn about the structure of proofs, and the kinds of logical arguments used to integrate and extend mathematical facts/topics.

The second theme is an appreciation for the "species" of mathematical objects and spaces that one might encounter. I think MATH-314 and MATH-403 are my favorite examples of this, but I should also mention MATH-305 for similar reasons. MATH-314 was interesting in that it cracks open several things we almost take for granted, such as calculus and the real number line. Calculus is incredibly far-reaching in its impact on technology and science, but we don't really get a sense for the mathematical results that provide its foundation until studying analysis. Similarly, linear algebra is deeply influential for modern computing, but I've grown to appreciate how useful it is for translating mathematical concepts into multiple dimensions. Being aware of the space(s) or set(s) of numbers you're reasoning about is crucial to framing the problems you're working on.

Unifying these two themes is an interest in computation and statistical inference. This stems from my motivations to pursue the degree, but my learning in MATH-462 and MATH-472 would have been much more shallow if I hadn't taken MATH-287 and MATH-314. Most importantly, courses like MATH-365, MATH-465, and MATH-472 emphasized the implementation of mathematical methods via programming and simulation. I've found that defining and conducting a simulation and implementing algorithms to be the best way I learn when exploring a mathematical property or topics within a course. Looking back, I think the absence of an application area was a reason I struggled with MATH-189 and MATH-305.
